common:
  meta_file_folder: './data/ESD/'

data:
  sampling_rate: 16000
  num_filter_bank: 40
  classes: [Angry, Happy, Neutral, Sad, Surprise]
  max_length: 300

model:
  in_channel: 3
  num_kernel1: 128
  num_kernel2: 256
  hidden_dim_cnn: 768
  hidden_dim_fc: 64
  cell_units: 128
  dropout_prob: 0.2 # dropout probability
  num_layers_lstm: 1 
  kernel_size: !!tuple [5, 3] # có thể sử dụng !! tuple[5, 3]
  max_pooling_size: !!tuple [2, 4] # ? tại sao các lớp pooling và filter không phải là ma trận vuông

train:
  train_batch_size: 256 # số lượng dữ liệu train một lần
  eval_batch_size: 32 # số lượng dữ liệu test một lần
  num_epochs: 5000 # số lượng epochs train
  learning_rate: 0.0001 # 
  momentum: 0.9 # hệ số momentum thuật toán tối ưu adam
  use_gpu: !!bool True

checkpoint:
  save_folder: './checkpoint/'
  continue_once: './checkpoint/model.pt'
  valid_interval: 300
